### ISSUE TITLE
Migrate remaining pipeline tasks to Node 10

### ISSUE THREAD

**Issue by anatolybolshakov** [microsoft/azure-pipelines-tasks#15183]
Since we are going to remove obsolete Node 6 execution handler - we need to migrate tasks which still use it - to Node 10:

- [x] ACRTaskV0 - removed the task due to being unused.
- [ ] AppCenterDistributeV1 - created [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15643). - need to fix tests
- [ ] AppCenterDistributeV2 - created [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15643). - need to fix tests
- [ ] AppCenterDistributeV3 - created [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15643). - need to fix tests
- [ ] AppCenterTest1 - created [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15700)
- [x] AzureIoTEdgeV2 - [ticket](https://github.com/microsoft/azure-pipelines-tasks/issues/15184)
- [ ] AzureMonitorAlerts - created [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15701)
- [x] AzureStaticWebAppV0
- [x] CondaEnvironmentV0 - [ticket](https://github.com/microsoft/azure-pipelines-tasks/issues/15189)
- [x] CondaEnvironmentV1  - [ticket](https://github.com/microsoft/azure-pipelines-tasks/issues/15189)
- [ ] ContainerStructureTestV0 - created [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15968)
- [x] CopyFilesV2
- [x] DownloadFileshareArtifactsV0 - [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15840)
- [ ] DownloadGithubNpmPackageV1 - created [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/16019)
- [x] DownloadGitHubNugetPackageV1 - created [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/16027)
- [x] JenkinsDownloadArtifactsV1 - [ticket](https://github.com/microsoft/azure-pipelines-tasks/issues/15185) [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15954)
- [x] MavenAuthenticateV0
- [x] NodeToolV0  - [ticket](https://github.com/microsoft/azure-pipelines-tasks/issues/15189)
- [ ] NpmAuthenticateV0 - [ticket](https://github.com/microsoft/azure-pipelines-tasks/issues/15533) - [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15900)
- [ ] NuGetCommandV2 - [ticket](https://github.com/microsoft/azure-pipelines-tasks/issues/15186)
- [x] NuGetInstallerV0 - [ticket](https://github.com/microsoft/azure-pipelines-tasks/issues/15186) - [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15828)
- [ ] NuGetPublisherV0 - [ticket](https://github.com/microsoft/azure-pipelines-tasks/issues/15186)
- [ ] NuGetRestoreV1 - created [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15855)
- [ ] NuGetToolInstallerV0 - created [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15822)
- [ ] NuGetToolInstallerV1 - created [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15824)
- [ ] NuGetV0 (deprecated)
- [ ] OpenPolicyAgentInstallerV0
- [x] PipAuthenticateV0 - created [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/16032)
- [x] PipAuthenticateV1 - created [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/16032)
- [x] PublishCodeCoverageResultsV2 - [ticket](https://github.com/microsoft/azure-pipelines-tasks/issues/15189)
- [ ] PublishTestResultsV1 - [ticket](https://github.com/microsoft/azure-pipelines-tasks/issues/15187)  - [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15907)
- [x] PyPIPublisherV0 - [ticket](https://github.com/microsoft/azure-pipelines-tasks/issues/15189) - closed as deprecated
- [x] ShellScriptV2 - [ticket](https://github.com/microsoft/azure-pipelines-tasks/issues/15189)
- [x] TwineAuthenticateV0 -  [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15924)
- [x] TwineAuthenticateV1 -  [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15924)
- [x] UniversalPackagesV0 -  [ticket](https://github.com/microsoft/azure-pipelines-tasks/issues/15186) - [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15848)
- [x] UseNodeV1 - [ticket](https://github.com/microsoft/azure-pipelines-tasks/issues/15189)
- [ ] VSTestV2 - created [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15798) 
- [x] XamarinTestCloudV1 - [ticket](https://github.com/microsoft/azure-pipelines-tasks/issues/15189)

**Comment by kasperk81** [comment]
@anatolybolshakov, node.js 10 is out of support: https://nodejs.org/en/about/releases/. why not target the current lts version to get a few years head start?

**Comment by anatolybolshakov** [comment]
@kasperk81 we are planning to move forward to the current lts nodejs version as well, although just going to make gradual migration - to make sure that there won't be issues caused by significant leap between node major versions.

**Comment by anatolybolshakov** [comment]
Created [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15643) for AppCenterDistributed tasks.

**Comment by DaniilShmelev** [comment]
ACRTask removal PRs:
https://github.com/microsoft/azure-pipelines-tasks/pull/15672
https://github.com/microsoft/azure-pipelines-tasks/pull/15674

**Comment by anatolybolshakov** [comment]
AppCenterTest1 - [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15700)

**Comment by anatolybolshakov** [comment]
AzureMonitorAlerts - [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15701)

**Comment by golubev-ivan** [comment]
VsTestV2 - [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15798)

**Comment by golubev-ivan** [comment]
NuGetToolInstallerV0-V1 PRs:
- https://github.com/microsoft/azure-pipelines-tasks/pull/15822
- https://github.com/microsoft/azure-pipelines-tasks/pull/15824

**Comment by anatolybolshakov** [comment]
NuGetInstallerV0 - [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15828)

**Comment by golubev-ivan** [comment]
DownloadFileshareArtifactsV0 - [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15840)

**Comment by golubev-ivan** [comment]
NuGetRestoreV1 - [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15855)

**Comment by DenisRumyantsev** [comment]
UniversalPackagesV0 — [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15848)

**Comment by tatyana-kostromskaya** [comment]
NpmAuthenticateV0 - [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15900)

**Comment by golubev-ivan** [comment]
DownloadGithubNpmPackageV1 - [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/16019)
ContainerStructureTestV0 - [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/15968)

**Comment by denis-tikhomirov** [comment]
DownloadGithubNugetPackageV1 - [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/16027)
PipAuthenticateV0 and PipAuthenticateV1 - [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/16032)

**Comment by denis-tikhomirov** [comment]
OpenPolicyAgentInstallerV0 - [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/16044)

**Comment by golubev-ivan** [comment]
NuGetCommandV2 - [PR](https://github.com/microsoft/azure-pipelines-tasks/pull/16054)
