### ISSUE TITLE
[REGRESSION]: Bash (3.231.1) is broken

### ISSUE THREAD

**Issue by jakubch1** [microsoft/azure-pipelines-tasks#19314]
### New issue checklist

- [ ] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [ ] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Bash

### Breaking task version

3.231.1

### Last working task version

3.231.0

### Regression Description

Task is failing with:

```
Starting: Build
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.231.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
/__a/externals/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__a/externals/node20/bin/node)
##[error]Exit code 1 returned from process: file name '/usr/bin/docker', arguments 'exec -i -u 1001  -w /home/vsts_azpcontainer 2db0ff203a011a6ad1858464cc4095d31398f69dd413a40fdade4ac57bdd0fd7 /__a/externals/node/bin/node /__w/_temp/containerHandlerInvoker.js'.
Finishing: Build
```

This is container (docker) case. Adding UseNode task is not helping - still version 20 is used.

Link: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8716922&view=logs&j=9e760a42-773c-55b7-f130-51b53c739723&t=832c56fa-26fb-5e45-496a-38822def881d

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [X] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Container: 'mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-20210301134114-d6e0352'

### Relevant log output

```shell
Starting: Build
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.231.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
/__a/externals/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__a/externals/node20/bin/node)
##[error]Exit code 1 returned from process: file name '/usr/bin/docker', arguments 'exec -i -u 1001  -w /home/vsts_azpcontainer 2db0ff203a011a6ad1858464cc4095d31398f69dd413a40fdade4ac57bdd0fd7 /__a/externals/node/bin/node /__w/_temp/containerHandlerInvoker.js'.
Finishing: Build
```

### Full task logs with system.debug enabled

Starting: Build
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.231.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
/__a/externals/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__a/externals/node20/bin/node)
##[error]Exit code 1 returned from process: file name '/usr/bin/docker', arguments 'exec -i -u 1001  -w /home/vsts_azpcontainer 2db0ff203a011a6ad1858464cc4095d31398f69dd413a40fdade4ac57bdd0fd7 /__a/externals/node/bin/node /__w/_temp/containerHandlerInvoker.js'.
Finishing: Build

### Repro steps

```yml
parameters:
      osDistribution: 'ubuntu'
      osDistributionTitle: 'Ubuntu'
      pool:
        vmImage: 'ubuntu-20.04'
      container: 'mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-20210301134114-d6e0352'
```

**Comment by DenisRumyantsev** [comment]
@jakubch1, thanks for reporting this issue! It should be already fixed. Please reopen this issue if you are still getting it.
