### ISSUE TITLE
[REGRESSION]: UseDotNet@2 fails to enumerate directory with Unicode characters while looking for global.json

### ISSUE THREAD

**Issue by bobbrow** [microsoft/azure-pipelines-tasks#19524]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

UseDotNet@2

### Breaking task version

2.235.1

### Last working task version

2.235.1

### Regression Description

Starting today, the UseDotNet task started failing in our build pipelines.  I am at a loss to explain why this is happening because it doesn't appear that the minor version of the task has changed.  The path that the task complains about is also not new to the repository. It was added in 2019.  It only fails on Windows agents.  macOS and linux (Ubuntu) seem to be ok.

Changing the task from:
```
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
```
to
```
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: false
    version: '8.0.100'
```
successfully works around the issue, but we'd like to pull in the version from global.json since it will affect our .NET builds when that value changes.

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows Server 2022

### Relevant log output

```shell
Starting: UseDotNet
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.235.1
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
##[error]Failed find: ENOENT: no such file or directory, stat 'D:\a\_work\1\s\<redacted>\utf_directory\ḋἲε𒑏○Ӳ'
Finishing: UseDotNet
```
```


### Full task logs with system.debug enabled

<details>
  <summary>UNSUCCESSFUL RUN</summary>
  <pre>2024-02-08T22:53:11.2478755Z ##[debug]Evaluating condition for step: 'UseDotNet'
2024-02-08T22:53:11.2479410Z ##[debug]Evaluating: SucceededNode()
2024-02-08T22:53:11.2479570Z ##[debug]Evaluating SucceededNode:
2024-02-08T22:53:11.2479892Z ##[debug]=> True
2024-02-08T22:53:11.2480057Z ##[debug]Result: True
2024-02-08T22:53:11.2480229Z ##[section]Starting: UseDotNet
2024-02-08T22:53:11.2559291Z ==============================================================================
2024-02-08T22:53:11.2559382Z Task         : Use .NET Core
2024-02-08T22:53:11.2559421Z Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
2024-02-08T22:53:11.2559570Z Version      : 2.235.1
2024-02-08T22:53:11.2559614Z Author       : Microsoft Corporation
2024-02-08T22:53:11.2559657Z Help         : https://aka.ms/AA4xgy0
2024-02-08T22:53:11.2559696Z ==============================================================================
2024-02-08T22:53:11.2811976Z ##[debug]Using node path: C:\vss-agent\3.232.3\externals\node20_1\bin\node.exe
2024-02-08T22:53:11.7855216Z ##[debug]agent.TempDirectory=D:\a\_work\_temp
2024-02-08T22:53:11.7867474Z ##[debug]loading inputs and endpoints
2024-02-08T22:53:11.7873179Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2024-02-08T22:53:11.7957383Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2024-02-08T22:53:11.7959966Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2024-02-08T22:53:11.7962943Z ##[debug]loading INPUT_INCLUDEPREVIEWVERSIONS
2024-02-08T22:53:11.7965952Z ##[debug]loading INPUT_INSTALLATIONPATH
2024-02-08T22:53:11.7968353Z ##[debug]loading INPUT_PACKAGETYPE
2024-02-08T22:53:11.7971009Z ##[debug]loading INPUT_PERFORMMULTILEVELLOOKUP
2024-02-08T22:53:11.7974171Z ##[debug]loading INPUT_USEGLOBALJSON
2024-02-08T22:53:11.7976556Z ##[debug]loading INPUT_WORKINGDIRECTORY
2024-02-08T22:53:11.7984625Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2024-02-08T22:53:11.7992220Z ##[debug]loaded 10
2024-02-08T22:53:11.7997039Z ##[debug]Agent.ProxyUrl=undefined
2024-02-08T22:53:11.7998559Z ##[debug]Agent.CAInfo=undefined
2024-02-08T22:53:11.7998813Z ##[debug]Agent.ClientCert=undefined
2024-02-08T22:53:11.7999000Z ##[debug]Agent.SkipCertValidation=undefined
2024-02-08T22:53:11.8362611Z ##[debug]Agent.ProxyUrl=undefined
2024-02-08T22:53:11.8362907Z ##[debug]Agent.CAInfo=undefined
2024-02-08T22:53:11.8363679Z ##[debug]Agent.ClientCert=undefined
2024-02-08T22:53:11.8365155Z ##[debug]check path : D:\a\_work\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.235.1\node_modules\azure-pipelines-tool-lib\lib.json
2024-02-08T22:53:11.8368865Z ##[debug]adding resource file: D:\a\_work\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.235.1\node_modules\azure-pipelines-tool-lib\lib.json
2024-02-08T22:53:11.8369135Z ##[debug]system.culture=en-US
2024-02-08T22:53:11.8520025Z ##[debug]Setting resource path to D:\a\_work\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.235.1\task.json
2024-02-08T22:53:11.8520388Z ##[debug]check path : D:\a\_work\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.235.1\task.json
2024-02-08T22:53:11.8520847Z ##[debug]adding resource file: D:\a\_work\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.235.1\task.json
2024-02-08T22:53:11.8521119Z ##[debug]system.culture=en-US
2024-02-08T22:53:11.8532161Z ##[debug]check path : D:\a\_work\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.235.1\node_modules\azure-pipelines-tasks-packaging-common\module.json
2024-02-08T22:53:11.8533068Z ##[debug]adding resource file: D:\a\_work\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.235.1\node_modules\azure-pipelines-tasks-packaging-common\module.json
2024-02-08T22:53:11.8533355Z ##[debug]system.culture=en-US
2024-02-08T22:53:11.8547718Z ##[debug]useGlobalJson=true
2024-02-08T22:53:11.8549922Z ##[debug]packageType=sdk
2024-02-08T22:53:11.8550264Z ##[debug]version=undefined
2024-02-08T22:53:11.8551862Z ##[debug]vsVersion=undefined
2024-02-08T22:53:11.8553243Z ##[debug]nugetVersion=undefined
2024-02-08T22:53:11.8553497Z ##[debug]installationPath=C:\ToolCache/dotnet
2024-02-08T22:53:11.8555523Z ##[debug]performMultiLevelLookup=false
2024-02-08T22:53:11.8557221Z ##[debug]includePreviewVersions=false
2024-02-08T22:53:11.8559240Z ##[debug]workingDirectory=D:\a\_work\1\s
2024-02-08T22:53:11.8561477Z ##[debug]agent.proxyurl=undefined
2024-02-08T22:53:11.8562080Z ##[debug]AZURE_HTTP_USER_AGENT=VSTS_011b8bdf-6d56-4f87-be0d-0092136884d9_build_16989_0
2024-02-08T22:53:11.8571660Z ##[debug]testing directory 'C:\ToolCache/dotnet'
2024-02-08T22:53:11.8572292Z ##[debug]testing directory 'C:\ToolCache'
2024-02-08T22:53:11.8573612Z ##[debug]mkdir 'C:\ToolCache/dotnet'
2024-02-08T22:53:11.8576642Z ##[debug]agent.proxyurl=undefined
2024-02-08T22:53:11.8577975Z ##[debug]AZURE_HTTP_USER_AGENT=VSTS_011b8bdf-6d56-4f87-be0d-0092136884d9_build_16989_0
2024-02-08T22:53:11.8581923Z ##[debug]defaultRoot: 'D:\a\_work\1\s'
2024-02-08T22:53:11.8582711Z ##[debug]findOptions.allowBrokenSymbolicLinks: 'false'
2024-02-08T22:53:11.8583114Z ##[debug]findOptions.followSpecifiedSymbolicLink: 'true'
2024-02-08T22:53:11.8583444Z ##[debug]findOptions.followSymbolicLinks: 'true'
2024-02-08T22:53:11.8583749Z ##[debug]findOptions.skipMissingFiles: 'false'
2024-02-08T22:53:11.8584045Z ##[debug]matchOptions.debug: 'false'
2024-02-08T22:53:11.8584515Z ##[debug]matchOptions.nobrace: 'true'
2024-02-08T22:53:11.8584933Z ##[debug]matchOptions.noglobstar: 'false'
2024-02-08T22:53:11.8585260Z ##[debug]matchOptions.dot: 'true'
2024-02-08T22:53:11.8585646Z ##[debug]matchOptions.noext: 'false'
2024-02-08T22:53:11.8586005Z ##[debug]matchOptions.nocase: 'true'
2024-02-08T22:53:11.8586414Z ##[debug]matchOptions.nonull: 'false'
2024-02-08T22:53:11.8586767Z ##[debug]matchOptions.matchBase: 'false'
2024-02-08T22:53:11.8587122Z ##[debug]matchOptions.nocomment: 'false'
2024-02-08T22:53:11.8587467Z ##[debug]matchOptions.nonegate: 'false'
2024-02-08T22:53:11.8587807Z ##[debug]matchOptions.flipNegate: 'false'
2024-02-08T22:53:11.8588161Z ##[debug]pattern: '**/global.json'
2024-02-08T22:53:11.8600581Z ##[debug]findPath: 'D:\a\_work\1\s'
2024-02-08T22:53:11.8600828Z ##[debug]statOnly: 'false'
2024-02-08T22:53:11.8601651Z ##[debug]findPath: 'D:\a\_work\1\s'
2024-02-08T22:53:11.8602021Z ##[debug]findOptions.allowBrokenSymbolicLinks: 'false'
2024-02-08T22:53:11.8602370Z ##[debug]findOptions.followSpecifiedSymbolicLink: 'true'
2024-02-08T22:53:11.8602694Z ##[debug]findOptions.followSymbolicLinks: 'true'
2024-02-08T22:53:11.8603163Z ##[debug]findOptions.skipMissingFiles: 'false'
2024-02-08T22:53:11.8605816Z ##[debug]  D:\a\_work\1\s (directory)

<snip - lots of directories printed out>

2024-02-08T22:53:15.2613731Z ##[debug]  D:\a\_work\1\s\<redacted>\utf_directory (directory)
2024-02-08T22:53:15.2647701Z ##[debug]task result: Failed
2024-02-08T22:53:15.2675819Z ##[error]Failed find: ENOENT: no such file or directory, stat 'D:\a\_work\1\s\<redacted>\utf_directory\ḋἲε𒑏○Ӳ'
2024-02-08T22:53:15.2682824Z ##[debug]Processed: ##vso[task.issue type=error;]Failed find: ENOENT: no such file or directory, stat 'D:\a\_work\1\s\<redacted>\utf_directory\ḋἲε𒑏○Ӳ'
2024-02-08T22:53:15.2688806Z ##[debug]Processed: ##vso[task.complete result=Failed;]Failed find: ENOENT: no such file or directory, stat 'D:\a\_work\1\s\<redacted>\utf_directory\ḋἲε𒑏○Ӳ'
2024-02-08T22:53:15.2785762Z ##[section]Finishing: UseDotNet </pre>
</details>

<details>
  <summary>SUCCESSFUL RUN</summary>
  <pre></pre>
</details>


### Repro steps

```yml
Not an open source repo.
I shared relevant yaml in the problem description.
```

**Comment by DenisRumyantsev** [comment]
@bobbrow, the `UseDotNetV2` task had a regression. Now it should be fixed, and task version `2.235.0` should be used in the pipeline. Can you please verify this?

**Comment by bobbrow** [comment]
I just tried again and 2.235.1 was still selected in my pipeline and the task failed.

**Comment by bobbrow** [comment]
It looks like 2.235.0 is being used now and we were able to switch back to `useGlobalJson: true`.  Thank you.

**Comment by bobbrow** [comment]
I spoke too soon.  Our builds are using 2.235.1 again.  I just decided to delete the offending paths before running UseDotNet since I don't need them in my pipeline.  The global.json got updated and we had to change the hardcoded version in our tasks, so I decided not to deal with this anymore.

**Comment by bobbrow** [comment]
Can you release the fix with a version number that's _newer_ than the latest version?  Perhaps that will cause the right version of the task to be deployed on our side.  The broken version is 2.235.1 and the working version is 2.235.0.

**Comment by g-timmerman** [comment]
I was searching for issues with Unicode, azure pipelines and the "ENOENT: no such file or directory" and found this issue as I was having similar issues with our pipeline.

Since task version 2.235.1 our pipeline fails with the .Net Core task for restore. It encountered files with Unicode characters in the filename (💙💚🧡) and fails with the "ENOENT: no such file or directory" message. We resolved it by removing these characters from the filename and the task succeeded again. Previous version 2.235.0 worked with same codebase and pipeline configuration.

- [x] hosted agent
- [x] windows-latest
- [x] 2.235.1
- [x] DotNetCoreCLI@2

**Comment by johnwc** [comment]
We are seeing similar thing with ubuntu, we have to manually set the `installationPath` parameter to `$(Agent.ToolsDirectory)/dotnet` for it to work, even though the [docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-dotnet-v2?view=azure-pipelines#inputs) state it should be that by default. Otherwise, we get a `cp: cannot create directory '/opt/hostedtoolcache/dotnet': No such file or directory` error. The odd thing though, on the agent it installs on, I see no v8 sdk installed in the `$(Agent.ToolsDirectory)/dotnet` directory.

**Comment by johnwc** [comment]
Still relevant
