### ISSUE TITLE
[BUG]: AzureWebApp@1- Error Description: Protocol "https:" not supported. Expected "http:"

### ISSUE THREAD

**Issue by KristofKuli** [microsoft/azure-pipelines-tasks#19639]
### New issue checklist

- [ ] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [ ] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureWebApp@1

### Task version

1.235.1

### Issue Description

The new version of AzureWebApp@1task is started to fail with the following error:
Error Description: Protocol "https:" not supported. Expected "http:"
The previous version, 1.235.0 did not have this issue. We are behind company proxy, hence the new version might have a proxy-handling problem.

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [X] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04

### Relevant log output

```shell
Got service connection details for Azure App Service:'as-mycmplianc-dev-processes-slz'
##[error][Thu, 14 Mar 2024 05:50:51 GMT] : @azure/msal-node@1.14.5 : Error - A non-MSALJS error was thrown while attempting to get the cloud instance discovery metadata.
Error: TypeError
Error Description: Protocol "https:" not supported. Expected "http:"
##[error][Thu, 14 Mar 2024 05:50:51 GMT] : @azure/msal-node@1.14.5 : Error - Did not find cloud discovery metadata from hardcoded values... Metadata could not be obtained from config, cache, network or hardcoded values. Throwing Untrusted Authority Error.
##[error][Thu, 14 Mar 2024 05:50:53 GMT] : @azure/msal-node@1.14.5 : Error - A non-MSALJS error was thrown while attempting to get the cloud instance discovery metadata.
Error: TypeError
Error Description: Protocol "https:" not supported. Expected "http:"
##[error][Thu, 14 Mar 2024 05:50:53 GMT] : @azure/msal-node@1.14.5 : Error - Did not find cloud discovery metadata from hardcoded values... Metadata could not be obtained from config, cache, network or hardcoded values. Throwing Untrusted Authority Error.
##[error][Thu, 14 Mar 2024 05:50:55 GMT] : @azure/msal-node@1.14.5 : Error - A non-MSALJS error was thrown while attempting to get the cloud instance discovery metadata.
Error: TypeError
Error Description: Protocol "https:" not supported. Expected "http:"
##[error][Thu, 14 Mar 2024 05:50:55 GMT] : @azure/msal-node@1.14.5 : Error - Did not find cloud discovery metadata from hardcoded values... Metadata could not be obtained from config, cache, network or hardcoded values. Throwing Untrusted Authority Error.
##[error][Thu, 14 Mar 2024 05:50:57 GMT] : @azure/msal-node@1.14.5 : Error - A non-MSALJS error was thrown while attempting to get the cloud instance discovery metadata.
Error: TypeError
Error Description: Protocol "https:" not supported. Expected "http:"
##[error][Thu, 14 Mar 2024 05:50:57 GMT] : @azure/msal-node@1.14.5 : Error - Did not find cloud discovery metadata from hardcoded values... Metadata could not be obtained from config, cache, network or hardcoded values. Throwing Untrusted Authority Error.
##[error]Error: Failed to get resource ID for resource type 'Microsoft.Web/Sites' and resource name 'as-mycmplianc-dev-processes-slz'. Error: Could not fetch access token for Azure. Status code: endpoints_resolution_error, status message: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.
Finishing: Azure App Deploy: as-mycmplianc-dev-processes-slz
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by LeftTwixWand** [comment]
@KristofKuli thank you for reaching us.
Can you please share a link to your pipeline run?
If you don't want to expose the link publicly - you can contact me by email: vhorbachov@microsoft.com

**Comment by KristofKuli** [comment]
Hi @LeftTwixWand,

Is it fine, if I send you the full log of the pipeline run?

**Comment by LeftTwixWand** [comment]
It would be good if you could send a full log for further investigation.
But we also need the link to the pipeline/release pipeline run, so we can apply the previous task version for you.

**Comment by LeftTwixWand** [comment]
@KristofKuli we're released a fix, can you please confirm, that the old version of the pipeline task is in use?

**Comment by KristofKuli** [comment]
Thanks, the rollback worked. The pipelines are successful, with the old version.

**Comment by fredericarkenauatdb** [comment]
@KristofKuli Im experiencing the same issue; however our Pipeline is still using 1.235.1; how did you roll back?

**Comment by KristofKuli** [comment]
@fredericarkenauatdb I didn't. @LeftTwixWand made a release. Please refer to his comment above.

**Comment by fredericarkenauatdb** [comment]
thanks! it automatically rolled back, I was just wondering because you said "it works" and my Pipeline was still using the broken Version (1.235.1)

but it is using the .0 Version again now

**Comment by qianz2** [comment]
@KristofKuli We've mitigated the issue by rolling back version, can you please share a link to your pipeline run and full logs so that we can start investigating it?
(You can send over by email: zqian@microsoft.com if you preferred)

**Comment by qianz2** [comment]
@KristofKuli We've released a fix to the task, and about to rollback to older version. Please let us know if you experience same issue again.
