### ISSUE TITLE
[REGRESSION]: No attachment pushed to results 

### ISSUE THREAD

**Issue by ChrystianC** [microsoft/azure-pipelines-tasks#19815]
### New issue checklist

- [ ] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [ ] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

PublishTestResults@2

### Regression Description

Publishing with test report Junit since last week doesn't attach a test results. Request is empty. I use visual regression `expect(page).toHaveScreenshot();`
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/91797794/4cd06fb1-5928-4a5a-9fc7-7e9b9575e566)

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [x] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20

### Relevant log output

```shell
Example preview
https://devblogs.microsoft.com/devops/junit-attachments-support-for-publish-test-results/
```

### Full task logs with system.debug enabled

<details>
  <summary>UNSUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

<details>
  <summary>SUCCESSFUL RUN</summary>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml
- script: 'yarn run test-e2e --reporter=junit'
    displayName: 'Yarn Test (E2E)'
    env:
      APP_DLL_DIR: '$(Build.BinariesDirectory)'
      COMMAND: '$(Agent.ToolsDirectory)/dotnet/dotnet TVMan.Client.dll'
      PLAYWRIGHT_JUNIT_OUTPUT_NAME: '$(Common.TestResultsDirectory)/e2e.xml'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results (E2E)'
    condition: succeededOrFailed()
    inputs:
      searchFolder: '$(Common.TestResultsDirectory)'
      testResultsFiles: 'e2e.xml'
      testRunTitle: 'E2E'
```

**Comment by sweco-nltbim** [comment]
Following.. I also run into the same issue. One day it stopped adding the attachments and can't figure out why.

**Comment by ashevchenkosps** [comment]
I've updated Playwright to 1.46 from 1.29, and now I see published artifacts but have zero in the attachments.
