### ISSUE TITLE
[BUG]:  Issue with Obsolete DockerCompose Version in Auto-generated File

### ISSUE THREAD

**Issue by fogwildflower** [microsoft/azure-pipelines-tasks#20129]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

DockerCompose

### Task version

1

### Issue Description

Hi, 

I'm encountering an issue with the DockerCompose@1 task in Azure DevOps, specifically related to an obsolete version of Docker Compose being used in the auto-generated file. Here's the problem I'm facing:

When using the DockerCompose@1 task to build docker images, I've recently updated Docker Compose on the agents. However, now I'm receiving warnings during execution that indicate an obsolete version in the auto-generated compose file:

##[error]time="2024-07-08T12:11:47Z" level=warning msg="/home/vsts/agents/3.241.0/.docker-compose.1720440594107.yml: `version` is obsolete"

It appears that this auto-generated compose file includes the version at the top, but I haven't found an option within the task to disable or update this to a non-obsolete version.

Any insights or guidance on how to address or work around this issue would be greatly appreciated.

Thank you!

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [X] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu Latest

### Relevant log output

```shell
##[error]time="2024-07-08T12:11:47Z" level=warning msg="/home/vsts/agents/3.241.0/.docker-compose.1720440594107.yml: `version` is obsolete"
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by ivanduplenskikh** [comment]
@fogwildflower, could you please clarify something for me? Are you experiencing this as a blocking error, or is it just a warning?
I ask that since my test pipeline shows this warning as an information message, the logs you've attached indicate an **##error**.

**Comment by pinkfloydx33** [comment]
We are also getting this, but on self-hosted/built VMSS Scaleset Agents. It's not a blocking error, but it is reported as an error on the pipeline *in red*:

```
##[error]time="2024-07-08T15:56:18Z" level=warning msg="/agent/.docker-compose.1720454178509.yml: `version` is obsolete"
```

**Comment by fogwildflower** [comment]
> We are also getting this, but on self-hosted/built VMSS Scaleset Agents. It's not a blocking error, but it is reported as an error on the pipeline _in red_:
> 
> ```
> ##[error]time="2024-07-08T15:56:18Z" level=warning msg="/agent/.docker-compose.1720454178509.yml: `version` is obsolete"
> ```
> 
> The file is definitely being generated by Azure DevOps _somehow_. We don't create the file and if I SSH into the agent after the pipeline has run, the file doesn't exist.

Thank you for your response, its a warning messages, showing as error, last night with deployed with this warning, everything is working.

**Comment by ViggoValfridsson** [comment]
I'm still experiencing this issue in my pipelines as well

**Comment by pinkfloydx33** [comment]
It's deploying, but that's besides the point. The message still shows up as an error on the pipeline which causes confusion for anyone reviewing the pipeline (say, because they are an Approver). The docker) compose file generation performed by Azure DevOps should be fixed

**Comment by fogwildflower** [comment]
> It's deploying, but that's besides the point. The message still shows up as an error on the pipeline which causes confusion for anyone reviewing the pipeline (say, because they are an Approver). The docker) compose file generation performed by Azure DevOps should be fixed

True

**Comment by ivanduplenskikh** [comment]
@TheVexy, @ViggoValfridsson, the PR #20197 changes have been rolled out.
Could you please confirm if the issue is resolved?

**Comment by satarr** [comment]
This is still an issue for me. The pipeline isn't blocked but haven't just updated the DockerCompose task to version 2 (DockerCompose@1) I am still seeing an error output within after execution.

`Starting: DockerCompose
==============================================================================
Task         : Docker Compose
Description  : Build, push or run multi-container Docker applications. Task can be used with Docker or Azure Container registry.
Version      : 1.243.1
Author       : Microsoft Corporation
Help         : https://aka.ms/azpipes-docker-compose-tsg
==============================================================================
##[error]time="2024-10-23T15:36:15Z" level=warning msg="/home/vsts/work/1/s/docker/docker-compose-test-db.yaml: `version` is obsolete"
/opt/hostedtoolcache/docker-stable/24.0.4/x64/docker compose -f /home/vsts/work/1/s/docker/docker-compose-test-db.yaml -f /home/vsts/agents/3.246.0/.docker-compose.1729697775698.yml -p cycle down
time="2024-10-23T15:36:15Z" level=warning msg="/home/vsts/work/1/s/docker/docker-compose-test-db.yaml: `version` is obsolete"

Finishing: DockerCompose
`

I see this item is closed as of August but the issue prevails.

**Comment by ivanduplenskikh** [comment]
@satarr  could you share your Docker Compose YAML file if possible, or alternatively, provide a minimal example YAML for reproducibility?
