### ISSUE TITLE
[BUG]: ##[error]Dotnet command failed with non-zero exit code on the following projects

### ISSUE THREAD

**Issue by jardelzinho** [microsoft/azure-pipelines-tasks#20343]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [ ] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

Dot Net Build

### Task version

2

### Issue Description

The pipeline which runs for .Net core 7.0.4 suddenly stops with exit code non-zero. Logs are not clear where is the issue. Also tried with a self hosted agent and outcome is the same. Using source inside agent it compiles using visual studio or dotnet tool. There was no changes in the pipeline between last successful execution and the failed one

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows-2022

### Relevant log output

```shell
##[error]Error: The process 'C:\hostedtoolcache\windows\dotnet\dotnet.exe' failed with exit code 1
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by jardelzinho** [comment]
From logs issue was identified
