### ISSUE TITLE
[BUG]: Version 2.245.1 Produces warning

### ISSUE THREAD

**Issue by linus66** [microsoft/azure-pipelines-tasks#20408]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

DotNetCoreCLI

### Task version

2.245.1

### Issue Description

DotNetCoreCLI@2 produces this warning
##[warning]Resource file has already set to: D:\a\_tasks\DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b\2.245.1\node_modules\azure-pipelines-tasks-packaging-common\module.json
Which make the BuildQualityChecks@9 fail
Not present in version 2.242.1

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [X] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Windows image tested

### Relevant log output

```shell
Starting: DotNet publish ....
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.245.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
##[warning]Resource file has already set to: D:\a\_tasks\DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b\2.245.1\node_modules\azure-pipelines-tasks-packaging-common\module.json
C:\Windows\system32\chcp.com 65001
Active code page: 65001
Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
C:\hostedtoolcache\windows\dotnet\dotnet.exe publish 

Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
Starting: DotNet publish ...
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.245.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
##[warning]Resource file has already set to: D:\a\_tasks\DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b\2.245.1\node_modules\azure-pipelines-tasks-packaging-common\module.json
C:\Windows\system32\chcp.com 65001
Active code page: 65001

Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
Finishing: DotNet publish ....
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by luislhg** [comment]
Getting the same here. Every dotnet task in a pipeline is throwing this warning now... each pipeline ends up with dozens of warnings...
Please let me know if you need more info (aside from what's already available).
Thanks

**Comment by abatishchev** [comment]
+1. It's a novelty in version `2.245.1` which wasn't in version `2.242.1`

**Comment by oatsoda** [comment]
This is good fun with a [Build Quality Checks](https://marketplace.visualstudio.com/items?itemName=mspremier.BuildQualityChecks) task checking that Warnings haven't increased!

**Comment by Gobikannan** [comment]
Same here.. plenty of warnings and also sonar is showing more warnings without any details about it.

Is it possible to use the previous version (2.242.1) which was working fine?

**Comment by abatishchev** [comment]
> This is good fun with a Build Quality Checks task checking that Warnings haven't increased!

Exactly what I'm dealing with right now.

> - task: DotNetCoreCLI@2.242.1

I think it's a very good workaround for now. Looking forward to something permanent.

**Comment by abatishchev** [comment]
Thanks to @ReneSchumacher, here's how to temporarily ignore the warnings in the quality check task:

```yaml
- task: BuildQualityChecks@9
  displayName: 'Check build quality'
  inputs:
    addAttachment: false
    checkWarnings: true
    warningThreshold: 0
    warningExclusions: |
      /\[warning\]Resource file has already set to/i
```

**Comment by lobbo232** [comment]
After spending a chunk of time implementing this on all our pipelines, the workaround works for us too.

I think this bug needs a little more urgency as it is blocking anybody using build quality checks. Is it worth considering rolling it back perhaps?

**Comment by stephajn** [comment]
By any chance, has this newer version of the task introduced some kind of bug with the memory usage? Doesn't matter if I use windows-latest or ubuntu-latest. All of my builds are out of the blue getting warnings about memory usage spiking to 95% and higher without us having changed anything in our build.

**Comment by Streammz** [comment]
Is this issue now resolved with the latest version? I see that a pull request regarding this issue has been merged, but the issue is still open. I just want to make sure before I revert my workaround.

**Comment by nietras** [comment]
We are hitting this every day now in every job run on devops. This means devs are less likely to catch **real** warnings and is incredibly annoying, how can we avoid this warning or expect a fix?

**Comment by HaochenQ** [comment]
Facing the same issue with DotNetCoreCLI@2.

**Comment by disouzam** [comment]
And besides that all other warnings are not showing up in the summary.

**Comment by wtrombly** [comment]
I am also experiencing this issue as of Friday last week.

**Comment by jojjebror** [comment]
I too am experiencing this warning in every pipeline build.

**Comment by jojjebror** [comment]
> Same here.. plenty of warnings and also sonar is showing more warnings without any details about it.
> 
> For now, i m running as below which seems fine.
> 
> `- task: DotNetCoreCLI@2.242.1 `

Can also confirm that this works as a workaround.

**Comment by ptemmer** [comment]
2.246.1 has been released

**Comment by himanshu-ram-punjabi** [comment]
Yes. v2.246.1 does not show up the warning. Thank you.
