### ISSUE TITLE
[BUG]: Failed to copy files for a specific release pipeline

### ISSUE THREAD

**Issue by naguaramaster** [microsoft/azure-pipelines-tasks#20491]
### New issue checklist

- [ ] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

CopyFilesOverSSH

### Task version

0.*

### Issue Description

I have a problem in a specific pipeline, which must copy a file to a remote destination and I get an error:

`2024-10-01T11:59:14.7214740Z Found 1 files to copy to the remote machine.
2024-10-01T11:59:14.7215725Z Copying file /Data_Build_Deploy/agente1/_work/r67/a/WSConsultaPoliza.war to /app/apache-tomcat-8.0.21/webapps/WSConsultaPoliza.war on remote machine.
2024-10-01T11:59:14.7312734Z ##[error]Failed to copy /Data_Build_Deploy/agente1/_work/r67/a/WSConsultaPoliza.war. Error: fastPut: Permission denied Local: /Data_Build_Deploy/agente1/_work/r67/a/WSConsultaPoliza.war Remote: /app/apache-tomcat-8.0.21/webapps/WSConsultaPoliza.war
    at fmtError (/Data_Build_Deploy/agente1/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.246.1/node_modules/ssh2-sftp-client/src/utils.js:55:18)
    at /Data_Build_Deploy/agente1/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.246.1/node_modules/ssh2-sftp-client/src/index.js:669:15
    at cbfinal (/Data_Build_Deploy/agente1/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.246.1/node_modules/ssh2/lib/protocol/SFTP.js:2239:11)
    at FSReqCallback.oncomplete (node:fs:192:23) {
  code: 3,
  custom: true
}
2024-10-01T11:59:14.7314728Z Completed copying 1 files to the remote machine.
2024-10-01T11:59:14.7315628Z ##[error]Failed to copy 1 files`

This error occurs only with this release pipeline, I tried with other releases that copy to the same destination and this does not occur. I've even created a new Build and Release Pipeline again and I still get the same error.
What could I check to solve this?
Thanks for your help

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

Azure DevOps Server (Please specify exact version in the textbox below)

### Operation system

Oracle Linux Server 7.9 Fedora

### Relevant log output

```shell
2024-10-01T11:59:13.8115995Z ##[section]Starting: Copiar archivos
2024-10-01T11:59:13.8122174Z ==============================================================================
2024-10-01T11:59:13.8122331Z Task         : Copy files over SSH
2024-10-01T11:59:13.8122433Z Description  : Copy files or build artifacts to a remote machine over SSH
2024-10-01T11:59:13.8122581Z Version      : 0.246.1
2024-10-01T11:59:13.8122675Z Author       : Microsoft Corporation
2024-10-01T11:59:13.8122789Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/copy-files-over-ssh
2024-10-01T11:59:13.8122928Z ==============================================================================
2024-10-01T11:59:13.8443490Z ##[command]/Data_Build_Deploy/agente1/externals/node20_1/bin/node -v
2024-10-01T11:59:13.8444178Z /Data_Build_Deploy/agente1/externals/node20_1/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /Data_Build_Deploy/agente1/externals/node20_1/bin/node)
2024-10-01T11:59:13.8444924Z /Data_Build_Deploy/agente1/externals/node20_1/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /Data_Build_Deploy/agente1/externals/node20_1/bin/node)
2024-10-01T11:59:13.8445770Z /Data_Build_Deploy/agente1/externals/node20_1/bin/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /Data_Build_Deploy/agente1/externals/node20_1/bin/node)
2024-10-01T11:59:13.8446694Z /Data_Build_Deploy/agente1/externals/node20_1/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /Data_Build_Deploy/agente1/externals/node20_1/bin/node)
2024-10-01T11:59:13.8447534Z /Data_Build_Deploy/agente1/externals/node20_1/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /Data_Build_Deploy/agente1/externals/node20_1/bin/node)
2024-10-01T11:59:13.8449748Z /Data_Build_Deploy/agente1/externals/node20_1/bin/node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /Data_Build_Deploy/agente1/externals/node20_1/bin/node)
2024-10-01T11:59:13.8582275Z ##[warning]The agent operating system doesn't support Node20. Using Node16 instead. Please upgrade the operating system of the agent to remain compatible with future updates of tasks: https://github.com/nodesource/distributions
2024-10-01T11:59:13.9867944Z Setting up SSH service connection to remote host 10.220.2.10.
2024-10-01T11:59:14.7214740Z Found 1 files to copy to the remote machine.
2024-10-01T11:59:14.7215725Z Copying file /Data_Build_Deploy/agente1/_work/r67/a/WSConsultaPoliza.war to /app/apache-tomcat-8.0.21/webapps/WSConsultaPoliza.war on remote machine.
2024-10-01T11:59:14.7312734Z ##[error]Failed to copy /Data_Build_Deploy/agente1/_work/r67/a/WSConsultaPoliza.war. Error: fastPut: Permission denied Local: /Data_Build_Deploy/agente1/_work/r67/a/WSConsultaPoliza.war Remote: /app/apache-tomcat-8.0.21/webapps/WSConsultaPoliza.war
    at fmtError (/Data_Build_Deploy/agente1/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.246.1/node_modules/ssh2-sftp-client/src/utils.js:55:18)
    at /Data_Build_Deploy/agente1/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.246.1/node_modules/ssh2-sftp-client/src/index.js:669:15
    at cbfinal (/Data_Build_Deploy/agente1/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.246.1/node_modules/ssh2/lib/protocol/SFTP.js:2239:11)
    at FSReqCallback.oncomplete (node:fs:192:23) {
  code: 3,
  custom: true
}
2024-10-01T11:59:14.7314728Z Completed copying 1 files to the remote machine.
2024-10-01T11:59:14.7315628Z ##[error]Failed to copy 1 files
2024-10-01T11:59:14.7438482Z ##[section]Finishing: Copiar archivos
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by naguaramaster** [comment]
The incident is resolved.

Not enough permission in the remote machine.
