### ISSUE TITLE
[BUG]: ARM template deployment - Can't find loc string for key: SettingAzureCloud

### ISSUE THREAD

**Issue by enachi** [microsoft/azure-pipelines-tasks#20497]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzureResourceManagerTemplateDeploymentV3

### Task version

3.246.3

### Issue Description

Since version v3.246.3, a warning message is being logged during the deployment process. The warning does not appear to have any effect on the deployment itself, and the application is deployed successfully. However, this warning gets logged in the summary of the pipeline run thus get users confused.

"##[warning]Can't find loc string for key: SettingAzureCloud"

With the previous version of the task (3.243.1), no warning logged.

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Microsoft Hosted
- [ ] Self-Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

none

### Operation system

ubuntu-latest

### Relevant log output

```shell
Starting: AzureResourceManagerTemplateDeployment
==============================================================================
Task         : ARM template deployment
Description  : Deploy an Azure Resource Manager (ARM) template to all the deployment scopes
Version      : 3.246.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
==============================================================================
ARM Service Connection deployment scope - Subscription
Checking if the following resource group exists: rg-*****-staging.
Resource group exists: true.
Creating deployment parameters.
##[warning]Can't find loc string for key: SettingAzureCloud
SettingAzureCloud AzureCloud
/usr/bin/az cloud set -n AzureCloud
.....
```

**Comment by TSL-Andrew** [comment]
I am seeing the same issue.
![image](https://github.com/user-attachments/assets/1c4dae8a-fbc4-4abc-ace3-4f44031f6428)

**Comment by cmicck** [comment]
Same thing here, also seems to be since yesterday 
![image](https://github.com/user-attachments/assets/97a11907-96f7-4c67-b428-7ca50c9486ef)

**Comment by komjera** [comment]
I am also experiencing this issue, I've never seen it before today. We are also using Microsoft hosted agents.

![image](https://github.com/user-attachments/assets/45fb5a25-f2ec-4af6-8840-51beef8f32e1)

**Comment by cbwalp** [comment]
I am experiencing as well, looks like it started for me on Monday, Sept. 30, 2024 - but I am using Self-Hosted Windows agents...
![image](https://github.com/user-attachments/assets/65457de9-3746-4942-8c43-76a26779c05a)

**Comment by azuresysadmin** [comment]
I am experiencing this issue as well, in several environments. All using Self-Hosted Linux agents, and it seems to have begun on September 30.

**Comment by cbwalp** [comment]
Hey @enachi - does this also have a companion report on https://developercommunity.visualstudio.com/ - if not, maybe putting it there and linking to here (and maybe back) would help get more attention?  Just a thought.

**Comment by twosatnams** [comment]
I'm also experiencing this issue when running a bicep file using Azure pipelines

**Comment by josiahmahachi** [comment]
I am following the lab on https://microsoftlearning.github.io/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/Instructions/Labs/AZ400_M02_L06_Deploy_Docker_containers_to_Azure_App_Service_web_apps.html and I am getting the same issue:

![image](https://github.com/user-attachments/assets/5e5d088d-a6a1-4941-aa84-5c9dab9a2e5a)

Has anyone found a solution yet?

**Comment by lluppesms** [comment]
Getting the same thing recently:
![image](https://github.com/user-attachments/assets/efd093aa-81fe-4c62-aa25-f38901e2f9c3)

**Comment by enachi** [comment]
> Hey [@enachi](https://github.com/enachi) - does this also have a companion report on https://developercommunity.visualstudio.com/ - if not, maybe putting it there and linking to here (and maybe back) would help get more attention? Just a thought.

[here is it](https://developercommunity.visualstudio.com/t/BUG:-ARM-template-deployment---Cant-f/10766097)
also, added it in the topic description

**Comment by omar-oropeza** [comment]
getting same error here:
![Image](https://github.com/user-attachments/assets/2bcd0ec4-7c35-41ed-afcd-5820b692f718)

**Comment by CribberSix** [comment]
Same here.

**Comment by Creddi** [comment]
Same here

**Comment by enachi** [comment]
`For anyone who’s facing the same issue here, please vote this ticket, with enough votes, I will try to engage the related team for a checking too.`

this is what we have to do. please vote for this issue on [dev comunity](https://developercommunity.visualstudio.com/t/BUG:-ARM-template-deployment---Cant-f/10766097). It's the same link, from the description

as a workaround, you can manually set the desired version like this
`- task: AzureResourceManagerTemplateDeployment@3.243.1`

**Comment by jelkevdh** [comment]
I'm having the same issua

**Comment by vandriot** [comment]
Same warning in my pipelines as well

**Comment by nikjuice** [comment]
Same

**Comment by sherman89** [comment]
Same here with version 3.247.5

**Comment by jkgwnne** [comment]
Same
![Image](https://github.com/user-attachments/assets/75ae64bb-99a6-4b6f-81ce-815b7941e9a9)

**Comment by MaxMommersteeg** [comment]
Same here. Running on self-hosted ubuntu agent.

**Comment by v-schhabra** [comment]
Hi Everyone,
Thanks for reporting this issue. 
Will investigate and try to share updates soon.

**Comment by dreuss-ka** [comment]
I'm also hitting this issue.

**Comment by PatrickBorkowicz** [comment]
Same here.

**Comment by pimenta888** [comment]
Same here

**Comment by pjnberndsen** [comment]
Same issue here.
```
ARM Service Connection deployment scope - Subscription
Checking if the following resource group exists: zom-weu-d-svc-managedidentities-rg.
Resource group exists: true.
Creating deployment parameters.
##[warning]Can't find loc string for key: SettingAzureCloud
SettingAzureCloud AzureCloud
C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" cloud set -n AzureCloud"
```

**Comment by Joeghanoe** [comment]
Same issue here

**Comment by enachi** [comment]
Hi @v-gayatrij 

I've noticed that your PRs have been merged into the main branch. Do you know when these changes will reflect in the Azure ARM deployment tasks? The issue still persists on my end.

Thanks

**Comment by bensmind** [comment]
Same issue

**Comment by v-gayatrij** [comment]
@enachi could you please share the version of the AzureResourceManagerTemplateDeployment task used in your pipeline?

> Hi [@v-gayatrij](https://github.com/v-gayatrij)
> 
> I've noticed that your PRs have been merged into the main branch. Do you know when these changes will reflect in the Azure ARM template deployment task v3? The issue still persists on my end.
> 
> Thanks

**Comment by MarkVerbaasRabo** [comment]
Seems like the issues are resolved in the current(?) version:
==============================================================================
Task         : ARM template deployment
Description  : Deploy an Azure Resource Manager (ARM) template to all the deployment scopes
Version      : 3.250.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
==============================================================================

No more warnings (on this). Thanks for the work.

**Comment by cbwalp** [comment]
Looks like the warnings have stopped on my side as well.  Thanks!

**Comment by JoelMiller74** [comment]
I can confirm that I am no longer having this issue after swithing back to AzureResourceManagerTemplateDeployment v3 (latest)
