### ISSUE TITLE
[BUG]: UsePythonVersion@0 task is unable to download 3.8.10

### ISSUE THREAD

**Issue by KristofKuli** [microsoft/azure-pipelines-tasks#20713]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [ ] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [ ] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

UsePythonVersion@0

### Task version

0.246.1

### Issue Description

The task is unable to download Python 3.8.10, as it is failing with the below error. This was working fine yesterday.
##[error]Failed to download Python from the Github Actions python registry (https://github.com/actions/python-versions). Error: Error: Could not find Python matching spec 3.8.10 (x86) in the python-versions registry. Beware that only systems listed in the Github Actions python versions manifest (https://github.com/actions/python-versions/blob/main/versions-manifest.json) are fit for downloading python on-flight. Also, proxy is not supported.
##[error]Version spec 3.8.10 for architecture x86 did not match any version in Agent.ToolsDirectory.

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [x] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04

### Relevant log output

```shell
##[error]Failed to download Python from the Github Actions python registry (https://github.com/actions/python-versions). Error: Error: Could not find Python matching spec 3.8.10 (x86) in the python-versions registry. Beware that only systems listed in the Github Actions python versions manifest (https://github.com/actions/python-versions/blob/main/versions-manifest.json) are fit for downloading python on-flight. Also, proxy is not supported.
##[error]Version spec 3.8.10 for architecture x86 did not match any version in Agent.ToolsDirectory.
```

### Full task logs with system.debug enabled

<details>
  <pre> [2024-12-06T09:20:27.8179463Z ##[debug]Evaluating condition for step: 'UsePythonVersion'
2024-12-06T09:20:27.8180393Z ##[debug]Evaluating: SucceededNode()
2024-12-06T09:20:27.8180701Z ##[debug]Evaluating SucceededNode:
2024-12-06T09:20:27.8181156Z ##[debug]=> True
2024-12-06T09:20:27.8181451Z ##[debug]Result: True
2024-12-06T09:20:27.8181730Z ##[section]Starting: UsePythonVersion
2024-12-06T09:20:27.8186852Z ==============================================================================
2024-12-06T09:20:27.8186995Z Task         : Use Python version
2024-12-06T09:20:27.8187095Z Description  : Use the specified version of Python from the tool cache, optionally adding it to the PATH
2024-12-06T09:20:27.8187237Z Version      : 0.246.1
2024-12-06T09:20:27.8187336Z Author       : Microsoft Corporation
2024-12-06T09:20:27.8187427Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/use-python-version
2024-12-06T09:20:27.8187576Z ==============================================================================
2024-12-06T09:20:29.1966994Z ##[debug]Agent environment resources - Disk: / Available 69179.93 MB out of 89902.71 MB, Memory: Used 1301.00 MB out of 7901.00 MB, CPU: Usage 7.00%
2024-12-06T09:20:29.6846219Z ##[debug]Using node path: /vsts/agent/externals/node20_1/bin/node
2024-12-06T09:20:29.7700976Z ##[debug]system.debug=True
2024-12-06T09:20:29.7701620Z ##[debug]DistributedTask.Tasks.Node.SkipDebugLogsWhenDebugModeOff=True
2024-12-06T09:20:29.7751716Z ##[debug]agent.TempDirectory=/workspace/_temp
2024-12-06T09:20:29.7758578Z ##[debug]loading inputs and endpoints
2024-12-06T09:20:29.7761586Z ##[debug]loading INPUT_VERSIONSPEC
2024-12-06T09:20:29.7775631Z ##[debug]loading INPUT_DISABLEDOWNLOADFROMREGISTRY
2024-12-06T09:20:29.7777019Z ##[debug]loading INPUT_ALLOWUNSTABLE
2024-12-06T09:20:29.7778985Z ##[debug]loading INPUT_ADDTOPATH
2024-12-06T09:20:29.7780327Z ##[debug]loading INPUT_ARCHITECTURE
2024-12-06T09:20:29.7781687Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2024-12-06T09:20:29.7782896Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2024-12-06T09:20:29.7784989Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2024-12-06T09:20:29.7789283Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2024-12-06T09:20:29.7791844Z ##[debug]loading SECRET_PASSWORD
2024-12-06T09:20:29.7793334Z ##[debug]loading SECRET_ACCESSKEY
2024-12-06T09:20:29.7795803Z ##[debug]loading SECRET_SMTPPW
2024-12-06T09:20:29.7803434Z ##[debug]loading SECRET_SHAREDSECRET
2024-12-06T09:20:29.7841521Z ##[debug]loading SECRET_AZURE_DEVOPS_EXT_PAT
2024-12-06T09:20:29.7842247Z ##[debug]loading SECRET_ARTIFACTPASSWORD
2024-12-06T09:20:29.7842681Z ##[debug]loaded 15
2024-12-06T09:20:29.8149041Z ##[debug]Agent.CAInfo=undefined
2024-12-06T09:20:29.8149502Z ##[debug]Agent.ClientCert=undefined
2024-12-06T09:20:29.8150019Z ##[debug]check path : /workspace/_tasks/UsePythonVersion_33c63b11-352b-45a2-ba1b-54cb568a29ca/0.246.1/node_modules/azure-pipelines-tool-lib/lib.json
2024-12-06T09:20:29.8151087Z ##[debug]adding resource file: /workspace/_tasks/UsePythonVersion_33c63b11-352b-45a2-ba1b-54cb568a29ca/0.246.1/node_modules/azure-pipelines-tool-lib/lib.json
2024-12-06T09:20:29.8151635Z ##[debug]system.culture=en-US
2024-12-06T09:20:29.8173166Z ##[debug]check path : /workspace/_tasks/UsePythonVersion_33c63b11-352b-45a2-ba1b-54cb568a29ca/0.246.1/task.json
2024-12-06T09:20:29.8173773Z ##[debug]adding resource file: /workspace/_tasks/UsePythonVersion_33c63b11-352b-45a2-ba1b-54cb568a29ca/0.246.1/task.json
2024-12-06T09:20:29.8174280Z ##[debug]system.culture=en-US
2024-12-06T09:20:29.8180191Z ##[debug]versionSpec=3.8.10
2024-12-06T09:20:29.8181694Z ##[debug]disableDownloadFromRegistry=false
2024-12-06T09:20:29.8182239Z ##[debug]allowUnstable=false
2024-12-06T09:20:29.8183933Z ##[debug]addToPath=true
2024-12-06T09:20:29.8184761Z ##[debug]architecture=x86
2024-12-06T09:20:29.8185192Z ##[debug]githubToken=undefined
2024-12-06T09:20:29.8189108Z ##[debug]Semantic version spec of 3.8.10 is 3.8.10
2024-12-06T09:20:29.8250302Z ##[warning]Specifying an exact version is not recommended on Microsoft-Hosted agents. Patch versions of Python can be replaced by new ones on Hosted agents without notice, which will cause builds to fail unexpectedly. It is recommended to specify only major or major and minor version (Example: `3` or `3.9`)
2024-12-06T09:20:29.8257197Z ##[debug]Processed: ##vso[task.issue type=warning;source=TaskInternal;correlationId=9756d77b-8421-44fd-8989-745f1b6d9f52;]Specifying an exact version is not recommended on Microsoft-Hosted agents. Patch versions of Python can be replaced by new ones on Hosted agents without notice, which will cause builds to fail unexpectedly. It is recommended to specify only major or major and minor version (Example: `3` or `3.9`)
2024-12-06T09:20:29.8258619Z ##[debug]isExplicit: 3.8.10
2024-12-06T09:20:29.8259095Z ##[debug]explicit? true
2024-12-06T09:20:29.8259718Z ##[debug]Agent.Version=3.248.0
2024-12-06T09:20:29.8260249Z ##[debug]Agent.ToolsDirectory=/workspace/_tool
2024-12-06T09:20:29.8260716Z ##[debug]checking cache: /workspace/_tool/Python/3.8.10/x86
2024-12-06T09:20:29.8261165Z ##[debug]not found
2024-12-06T09:20:29.8261608Z ##[debug]Could not find a local python installation matching 3.8.10.
2024-12-06T09:20:29.8262090Z ##[debug]Trying to download python from registry.
2024-12-06T09:20:29.8263170Z ##[warning]You should provide GitHub token if you want to download a python release. Otherwise you may hit the GitHub anonymous download limit.
2024-12-06T09:20:29.8263952Z ##[debug]Processed: ##vso[task.issue type=warning;source=TaskInternal;correlationId=9756d77b-8421-44fd-8989-745f1b6d9f52;]You should provide GitHub token if you want to download a python release. Otherwise you may hit the GitHub anonymous download limit.
2024-12-06T09:20:29.8264604Z ##[debug]Downloading manifest
2024-12-06T09:20:30.3046034Z ##[error]Failed to download Python from the Github Actions python registry (https://github.com/actions/python-versions). Error: Error: Could not find Python matching spec 3.8.10 (x86) in the python-versions registry. Beware that only systems listed in the Github Actions python versions manifest (https://github.com/actions/python-versions/blob/main/versions-manifest.json) are fit for downloading python on-flight. Also, proxy is not supported.
2024-12-06T09:20:30.3047427Z ##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;correlationId=9756d77b-8421-44fd-8989-745f1b6d9f52;]Failed to download Python from the Github Actions python registry (https://github.com/actions/python-versions). Error: Error: Could not find Python matching spec 3.8.10 (x86) in the python-versions registry. Beware that only systems listed in the Github Actions python versions manifest (https://github.com/actions/python-versions/blob/main/versions-manifest.json) are fit for downloading python on-flight. Also, proxy is not supported.
2024-12-06T09:20:30.3048798Z ##[debug]Agent.Version=3.248.0
2024-12-06T09:20:30.3049813Z ##[debug]Agent.ToolsDirectory=/workspace/_tool
2024-12-06T09:20:30.3050448Z ##[debug]Agent.Version=3.248.0
2024-12-06T09:20:30.3051062Z ##[debug]Agent.ToolsDirectory=/workspace/_tool
2024-12-06T09:20:30.3051698Z ##[debug]Agent.ToolsDirectory=/workspace/_tool
2024-12-06T09:20:30.3052298Z ##[debug]task result: Failed
2024-12-06T09:20:30.3053738Z ##[error]Version spec 3.8.10 for architecture x86 did not match any version in Agent.ToolsDirectory.
Versions in /workspace/_tool:

If this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Python at https://aka.ms/hosted-agent-software.
If this is a self-hosted agent, see how to configure side-by-side Python versions at https://go.microsoft.com/fwlink/?linkid=871498.
2024-12-06T09:20:30.3054740Z ##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;correlationId=9756d77b-8421-44fd-8989-745f1b6d9f52;]Version spec 3.8.10 for architecture x86 did not match any version in Agent.ToolsDirectory.
Versions in /workspace/_tool:

If this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Python at https://aka.ms/hosted-agent-software.
If this is a self-hosted agent, see how to configure side-by-side Python versions at https://go.microsoft.com/fwlink/?linkid=871498.
2024-12-06T09:20:30.3057481Z ##[debug]Processed: ##vso[task.complete result=Failed;]Version spec 3.8.10 for architecture x86 did not match any version in Agent.ToolsDirectory.
Versions in /workspace/_tool:

If this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Python at https://aka.ms/hosted-agent-software.
If this is a self-hosted agent, see how to configure side-by-side Python versions at https://go.microsoft.com/fwlink/?linkid=871498.
2024-12-06T09:20:30.3115300Z ##[section]Finishing: UsePythonVersion
] </pre>
</details>

### Repro steps

```yml
- task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8.10'
      addToPath: true
      architecture: 'x86'
```

**Comment by praval-microsoft** [comment]
Could you please verify if the requirements mentioned [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-python-version-v0?view=azure-pipelines#how-can-i-configure-a-self-hosted-agent-to-use-this-task) are being met for the self-hosted agent? 

Additionally, please take note of this.
![Image](https://github.com/user-attachments/assets/f95c6729-5ce0-4426-bfba-8de71193b80f)
