### ISSUE TITLE
[BUG]: Workflow Labeler fails with error: npm error Unable to authenticate, your authentication token seems to be invalid.

### ISSUE THREAD

**Issue by abatishchev** [microsoft/azure-pipelines-tasks#20732]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

N/A

### Task version

N/A

### Issue Description

Error:

```
npm error code E401
npm error Unable to authenticate, your authentication token seems to be invalid.
npm error To correct this please try logging in again with:
npm error   npm login
```

See https://github.com/microsoft/azure-pipelines-tasks/actions/runs/12340684271/job/34438443983#step:5:43

See also:

1.https://github.com/microsoft/azure-pipelines-tasks/issues/18732
2. https://github.com/microsoft/azure-pipelines-tasks/issues/17253

### Environment type (Please select at least one enviroment where you face this issue)

- [ ] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container
- [x] N/A

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Azure DevOps Server Version (if applicable)

N/A

### Operation system

N/A

### Relevant log output

N/A

### Full task logs with system.debug enabled

N/A

### Repro steps

N/A

**Comment by v-schhabra** [comment]
Hi @abatishchev 
Please follow this doc to create token. https://dev.azure.com/mseng/PipelineTools/_artifacts/feed/PipelineTools_PublicPackages/connect
If you have any doubts please let us know.

**Comment by abatishchev** [comment]
Hi @v-schhabra,
Does every user who opens an issue in this repo need to create a token for the repo's housekeeping workflow (per my understanding what the labler does) could function?

**Comment by v-schhabra** [comment]
Hi @abatishchev 
No, users don’t need to create tokens for such workflows to function.
Could you please share me your alias so that I can share you the doc which you need to follow to create token for the above issue.

**Comment by abatishchev** [comment]
Hi @v-schhabra,
I'm like a regular user then. I just filed an issue in this repo and noticed the Labeler workflow has failed, hence filed this one.
Makes sense?
