### ISSUE TITLE
Pattern matching consistency

### ISSUE THREAD

**Issue by ericsciple** [microsoft/azure-pipelines-tasks#5043]
## Goals:

1. For inputs that accept a glob pattern, the helpmarkdown for the input should provide a link for users to understand what syntax is supported.<br /><br />Ideally this should be a link to the task's help topic (see the Copy Files task). This allows the task's help topic to give specific examples (relevant to that task). And then the task's help topic links over to the generic syntax reference document.<br /><br />For any tasks without a help topic in place, a low cost alternative is available. Add an FWLINK to the input helpmarkdown that links to the pattern syntax reference: [https://go.microsoft.com/fwlink/?linkid=856077](https://go.microsoft.com/fwlink/?linkid=856077)

2. All in-the-box tasks should expose a consistent globbing experience. Some tasks are using the old, proprietary pattern matching library. And less severe, some tasks are using an older version of the task lib, before a consistent set of recommended default options was added (vsts-task-lib 2.x). [Task author guidance is here](https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/findingfiles.md).

## Task changes

The following tasks either have an input that does not have a link, or are using the old, proprietary pattern matching library.

- [ ] AndroidSigning - files - Needs link
- [ ] ANT - testResultsFiles - Needs link
- [ ] AzureCloudPowerShellDeployment - csCfg - Needs link
- [ ] AzureCloudPowerShellDeployment - csPkg - Needs link
- [ ] AzureResourceGroupDeployment - csmFile - Needs link
- [ ] AzureRmWebAppDeployment - Package - Needs link
- [ ] AzureRmWebAppDeployment - JSONFiles - Needs link
- [ ] IISWebAppDeploymentOnMachineGroup - Package - Needs link
- [ ] IISWebAppDeploymentOnMachineGroup - JSONFiles - Needs link
- [ ] cURLUploader - files - Needs link
- [ ] DeleteFiles - https://www.visualstudio.com/en-us/docs/build/steps/utility/delete-files - Doc needs to link to reference
- [ ] Docker - dockerFile - Needs link
- [ ] DockerCompose - dockerComposeFile - Needs link
- [ ] DotNetCoreCLI - projects - Needs link
- [ ] DotNetCoreCLI - searchPatternPack - Needs link
- [ ] DotNetCoreCLI - searchPatternPush - Needs link
- [ ] Gradle - testResultsFiles - Needs link
- [ ] Grunt - testResultsFiles - Needs link
- [ ] Gulp - testResultsFiles - Needs link
- [ ] Gulp - testFiles - Needs link
- [ ] Maven - testResultsFiles - Needs link
- [ ] MSBuild - solution - Needs link, needs to use new lib on Windows
- [ ] NuGetCommand - solution - Needs link
- [ ] NuGetCommand - searchPatternPush - Needs link
- [ ] NuGetCommand - searchPatternPack - Needs link
- [ ] PackerBuild - packagePath - Needs link
- [ ] PackerBuild - deployScriptPath - Needs link
- [ ] PublishCodeCoverageResults - additionalCodeCoverageFiles - Needs link
- [ ] PublishCodeCoverageResults - summaryFileLocation - Needs link
- [ ] PublishCodeCoverageResults - reportDirectory - Needs link
- [ ] ServiceFabricComposeDeploy - Needs to use new lib
- [ ] ServiceFabricDeploy - Needs to use new lib
- [ ] ServiceFabricUpdateAppVersions - Needs to use new lib
- [ ] SqlAzureDacpacDeployment - Needs to use new lib
- [ ] SqlDacpacDeploymentOnMachineGroup - Needs to use new lib
- [ ] VSBuild - Needs to use new lib
- [ ] VSMobileCenterUpload - pdbPath - Needs link
- [ ] VSMobileCenterUpload - dsymPath - Needs link
- [ ] XamarinAndroid - project - Needs link, needs to use new lib
- [ ] XamarinTestCloud - app - Needs link
- [ ] XamarinTestCloud - dsym - Needs link
- [ ] XamarinTestCloud - testCloudLocation - Needs link
- [ ] Xcode - xcWorkspacePath - Needs link

**Comment by eschrader** [comment]
Thanks Eric for identifying this issue. I believe this is what is preventing me from excluding files from VS TS to an Azure Web App using FTP Copy. How can I exclude files, aside from adding a Cloak on the get source for the entire project? I have quote a few filters I want for files I want to exclude:

1. **
2. !**/wwwRoot/assets/**
3. !**/wwwRoot/App_Data/**
4. !**/wwwRoot/App_Start/**
5. !**/wwwRoot/bower_components/**
6. !**/wwwRoot/Controllers/**
7. !**/wwwRoot/Hidden/**
8. !**/wwwRoot/features/**
9. !**/wwwRoot/Misc/**
10. !**/wwwRoot/packages/**
11. !**/wwwRoot/Properties/**
12. !**/wwwRoot/Repository/**
13. !**/Config.js
14. !**/wwwRoot/bower.json
15. !**.cs
16. !**/wwwRoot/gulpfile.js
17. !**/wwwRoot/package.json
18. !**.csproj
19. !**.vspscc
20. !**.sln
21. !**.vssscc
22. !**/wwwRoot/Testing123.html
23. !**.config

Is this issue just about updating documentation on the help tooltips, or is there an issue with it is currently impossible to exclude files? Maybe if its the prior, let me know how I can filter files and folder from an FTP copy task until the help documentation is updated.

The client is really pushing me to automate the manual FTP deployment we have right now to the Azure Web App. I was able to use similar filters to filter Copy Files over SSH for another task we use to copy files to Linux Ubuntu 14 which work great.

Please let me know a work around on filtering files/folders from an FTP copy or an estimate of how long this issue will be resolved. (also I consider this a bug more than an enhancement if the filtering of files is broken in the pattern matching box).

**Comment by eschrader** [comment]
Hi Eric, thank you for the workaround, copying the files to a folder in the build staging directory (with filters) then copying all items from there to the FTP copy task worked.

**Comment by rickyno** [comment]
I didn't want to create a new issue as I believe this is related to pattern matching consistency, if not please consider the following if there is a pattern matching update in the pipeline.

I used the ** pattern with the **DeleteFiles** task to empty the sources directory as the last build step, assuming it would clear the entire directory, but dotted folders and files are ignored. 

The `.nuget `folder and `.tfignore` file are still present after the build completes, everything else is cleared as expected.

**Comment by pjquirk** [comment]
I updated the following tasks:
- ANT
- AndroidSigning
- Gradle
- Maven
- XamarinAndroid
- XamarinTestCloud
- Xcode

**Comment by leantk** [comment]
This issue is stale because it has been open for a year with no activity. Remove the stale label or comment on the issue otherwise this will be closed in 5 days

**Comment by damccorm** [comment]
Closing as this has gone stale. It looks like the issue has since been fixed in a bunch of places anyways, I don't think we want to make the breaking changes required for this at this point anyways without customer demand
